name: Build and Deploy

on:
    push:
        branches:
            - main

env:
    LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
    AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
    id-token: write
    contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Zip files
              run: zip -r lambda.zip .

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Upload to Lambda
              run: aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --zip-file fileb://lambda.zip
